#!/bin/bash

set -e
ABSOLUTE_PATH="$(readlink -f "$0")"
DIR="$(dirname ${ABSOLUTE_PATH})"

for HOOK_PATH in ${DIR}/pre-commit-*; do
    HOOK=$(basename ${HOOK_PATH})
    trap "echo ${HOOK} finished abnormally" EXIT
    echo "Running hook ${HOOK}..."
    ${HOOK_PATH}
    echo "Hook ${HOOK} finished succesfully"
done

